name = "durable-objects-demo"
main = "src/index.js"
compatibility_date = "2023-01-12"

[durable_objects]
bindings = [{name = "AVATAR", class_name = "Avatar"}]

[[migrations]]
tag = "v1"
new_classes = ["Avatar"]